In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
AdvWorksCusts = pd.read_csv('C:\\Users\\user\Downloads\microsoft datascience\FinalExam\AdvWorksCusts.csv')
AW_AveMonthSpend = pd.read_csv('C:\\Users\\user\Downloads\microsoft datascience\FinalExam\AW_AveMonthSpend.csv')
AW_BikeBuyer = pd.read_csv('C:\\Users\\user\Downloads\microsoft datascience\FinalExam\AW_BikeBuyer.csv')

In [3]:
Adventureworks = AdvWorksCusts.merge(AW_AveMonthSpend, on='CustomerID')

In [4]:
merged = Adventureworks.merge(AW_BikeBuyer, on='CustomerID')

In [5]:
merged


CustomerID Title   FirstName MiddleName   LastName Suffix  \
0           11000   NaN         Jon          V       Yang    NaN   
1           11001   NaN      Eugene          L      Huang    NaN   
2           11002   NaN       Ruben        NaN     Torres    NaN   
3           11003   NaN     Christy        NaN        Zhu    NaN   
4           11004   NaN   Elizabeth        NaN    Johnson    NaN   
5           11005   NaN       Julio        NaN       Ruiz    NaN   
6           11006   NaN       Janet          G    Alvarez    NaN   
7           11007   NaN       Marco        NaN      Mehta    NaN   
8           11008   NaN         Rob        NaN    Verhoff    NaN   
9           11009   NaN     Shannon          C    Carlson    NaN   
10          11010   NaN   Jacquelyn          C     Suarez    NaN   
11          11011   NaN      Curtis        NaN         Lu    NaN   
12          11012   NaN      Lauren          M     Walker    NaN   
13          11013   NaN         Ian          M    Jenkins    NaN   
14          11014   NaN      Sydney        NaN    Bennett    NaN   
15          11015   NaN       Chloe        NaN      Young    NaN   
16          11016   NaN       Wyatt          L       Hill    NaN   
17          11019   NaN        Luke          L        Lal    NaN   
18          11020   NaN      Jordan          C       King    NaN   
19          11023   NaN        Seth          M    Edwards    NaN   
20          11024   NaN     Russell        NaN        Xie    NaN   
21          11025   NaN   Alejandro        NaN       Beck    NaN   
22          11026   NaN      Harold        NaN        Sai    NaN   
23          11027   NaN      Jessie          R       Zhao    NaN   
24          11028   NaN        Jill        NaN    Jimenez    NaN   
25          11031   NaN     Theresa          G      Ramos    NaN   
26          11032   NaN      Denise        NaN      Stone    NaN   
27          11033   NaN       Jaime        NaN       Nath    NaN   
28          11034   NaN       Ebony        NaN   Gonzalez    NaN   
29          11035   NaN       Wendy        NaN  Dominguez    NaN   
...           ...   ...         ...        ...        ...    ...   
17179       29451   NaN    Geoffrey          A      Lopez    NaN   
17180       29452   NaN    Meredith          J     Romero    NaN   
17181       29454   NaN    Victoria        NaN    Bradley    NaN   
17182       29455   NaN        Dawn          D       Zeng    NaN   
17183       29456   NaN     Lindsay        NaN        She    NaN   
17184       29457   NaN     Cynthia        NaN     Kapoor    NaN   
17185       29458   NaN       Danny          M     Moreno    NaN   
17186       29460   NaN      Andres          E    Chander    NaN   
17187       29461   NaN       Colin          C         Xu    NaN   
17188       29462   NaN     Clinton        NaN  Hernandez    NaN   
17189       29463   NaN       Lucas        NaN   Gonzales    NaN   
17190       29464   NaN      Eugene        NaN        Gao    NaN   
17191       29465   NaN         Roy        NaN       Gill    NaN   
17192       29466   NaN       Lance        NaN    Jimenez    NaN   
17193       29467   NaN      Monica          J      Mehta    NaN   
17194       29468   NaN  Jacqueline          H     Morris    NaN   
17195       29469   NaN   Dominique          M   Saunders    NaN   
17196       29470   NaN      Nathan        NaN    Roberts    NaN   
17197       29471   NaN        Dana        NaN     Ortega    NaN   
17198       29472   NaN       Lacey          M     Sharma    NaN   
17199       29473   NaN      Carmen          J     Subram    NaN   
17200       29474   NaN       Jaime          B       Raje    NaN   
17201       29475   NaN       Jared          A       Ward    NaN   
17202       29476   NaN   Elizabeth        NaN    Bradley    NaN   
17203       29477   NaN        Neil          N       Ruiz    NaN   
17204       29478   NaN      Darren          D    Carlson    NaN   
17205       29479   NaN       Tommy          L       Tang    Na

In [6]:
merged.drop(['Title','Suffix','AddressLine2'], axis = 1, inplace=True)

In [7]:
merged.CustomerID.unique().shape

(16404,)

In [8]:
merged.shape

(17209, 22)

In [9]:
merged['AveMonthSpend'].mean()

72.49462490557266

In [10]:
list(merged.columns.values)

['CustomerID',
 'FirstName',
 'MiddleName',
 'LastName',
 'AddressLine1',
 'City',
 'StateProvinceName',
 'CountryRegionName',
 'PostalCode',
 'PhoneNumber',
 'BirthDate',
 'Education',
 'Occupation',
 'Gender',
 'MaritalStatus',
 'HomeOwnerFlag',
 'NumberCarsOwned',
 'NumberChildrenAtHome',
 'TotalChildren',
 'YearlyIncome',
 'AveMonthSpend',
 'BikeBuyer']

In [11]:
merged.drop_duplicates(subset ='CustomerID',keep='last', inplace=True)

In [12]:
merged


CustomerID   FirstName MiddleName   LastName  \
0           11000         Jon          V       Yang   
1           11001      Eugene          L      Huang   
2           11002       Ruben        NaN     Torres   
3           11003     Christy        NaN        Zhu   
4           11004   Elizabeth        NaN    Johnson   
5           11005       Julio        NaN       Ruiz   
6           11006       Janet          G    Alvarez   
7           11007       Marco        NaN      Mehta   
8           11008         Rob        NaN    Verhoff   
9           11009     Shannon          C    Carlson   
10          11010   Jacquelyn          C     Suarez   
11          11011      Curtis        NaN         Lu   
12          11012      Lauren          M     Walker   
13          11013         Ian          M    Jenkins   
14          11014      Sydney        NaN    Bennett   
15          11015       Chloe        NaN      Young   
16          11016       Wyatt          L       Hill   
17          11019        Luke          L        Lal   
18          11020      Jordan          C       King   
19          11023        Seth          M    Edwards   
20          11024     Russell        NaN        Xie   
21          11025   Alejandro        NaN       Beck   
22          11026      Harold        NaN        Sai   
23          11027      Jessie          R       Zhao   
24          11028        Jill        NaN    Jimenez   
25          11031     Theresa          G      Ramos   
26          11032      Denise        NaN      Stone   
27          11033       Jaime        NaN       Nath   
28          11034       Ebony        NaN   Gonzalez   
29          11035       Wendy        NaN  Dominguez   
...           ...         ...        ...        ...   
17179       29451    Geoffrey          A      Lopez   
17180       29452    Meredith          J     Romero   
17181       29454    Victoria        NaN    Bradley   
17182       29455        Dawn          D       Zeng   
17183       29456     Lindsay        NaN        She   
17184       29457     Cynthia        NaN     Kapoor   
17185       29458       Danny          M     Moreno   
17186       29460      Andres          E    Chander   
17187       29461       Colin          C         Xu   
17188       29462     Clinton        NaN  Hernandez   
17189       29463       Lucas        NaN   Gonzales   
17190       29464      Eugene        NaN        Gao   
17191       29465         Roy        NaN       Gill   
17192       29466       Lance        NaN    Jimenez   
17193       29467      Monica          J      Mehta   
17194       29468  Jacqueline          H     Morris   
17195       29469   Dominique          M   Saunders   
17196       29470      Nathan        NaN    Roberts   
17197       29471        Dana        NaN     Ortega   
17198       29472       Lacey          M     Sharma   
17199       29473      Carmen          J     Subram   
17200       29474       Jaime          B       Raje   
17201       29475       Jared          A       Ward   
17202       29476   Elizabeth        NaN    Bradley   
17203       29477        Neil          N       Ruiz   
17204       29478      Darren          D    Carlson   
17205       29479       Tommy          L       Tang   
17206       29480        Nina          W       Raji   
17207       29481        Ivan        NaN       Suri   
17208       29482     Clayton        NaN      Zhang   

                      AddressLine1             City    StateProvinceName  \
0                  3761 N. 14th St      Rockhampton           Queensland   
1                       2243 W St.          Seaford             Victoria   
2                 5844 Linden Land           Hobart             Tasmania   
3                 1825 Village Pl.       North Ryde      New South Wales   
4              7553 Harness Circle       Wollongong      New South Wales   
5              7305 Humphrey Drive    East Brisbane           Queensland   
6                    2612 Berry Dr       Matraville      New Sou

In [13]:
print (merged.shape)
print (merged.CustomerID.unique().shape)

(16404, 22)
(16404,)


In [14]:
from dateutil.parser import parse 
from datetime import datetime

def generate_age(customer_info, format):
    collection_day = birthday = datetime(2019, 1, 1, 0, 0, 0)
    age = []
    for index, row in customer_info.iterrows():
        conv = datetime.strptime(row['BirthDate'], format)
        age.append(int((collection_day - conv).days/365))
    return age


In [15]:

merged['Age'] = generate_age(merged, '%Y-%m-%d')

In [16]:
merged.columns

Index(['CustomerID', 'FirstName', 'MiddleName', 'LastName', 'AddressLine1',
       'City', 'StateProvinceName', 'CountryRegionName', 'PostalCode',
       'PhoneNumber', 'BirthDate', 'Education', 'Occupation', 'Gender',
       'MaritalStatus', 'HomeOwnerFlag', 'NumberCarsOwned',
       'NumberChildrenAtHome', 'TotalChildren', 'YearlyIncome',
       'AveMonthSpend', 'BikeBuyer', 'Age'],
      dtype='object')

In [17]:
merged['Age'] += 1

In [18]:
x = merged.loc[:,['CustomerID','YearlyIncome','Gender','Age']].values

In [19]:
x


array([[11000, 137947, 'M', 53],
       [11001, 101141, 'M', 54],
       [11002, 91945, 'M', 54],
       ...,
       [29480, 60417, 'F', 59],
       [29481, 66653, 'M', 60],
       [29482, 59736, 'M', 60]], dtype=object)

In [20]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x = LabelEncoder()
x[:,2] = labelencoder_x.fit_transform(x[:,2])
onehotencoder = OneHotEncoder(categorical_features=[2])
x = onehotencoder.fit_transform(x).toarray()

In [21]:
x

array([[0.00000e+00, 1.00000e+00, 1.10000e+04, 1.37947e+05, 5.30000e+01],
       [0.00000e+00, 1.00000e+00, 1.10010e+04, 1.01141e+05, 5.40000e+01],
       [0.00000e+00, 1.00000e+00, 1.10020e+04, 9.19450e+04, 5.40000e+01],
       ...,
       [1.00000e+00, 0.00000e+00, 2.94800e+04, 6.04170e+04, 5.90000e+01],
       [0.00000e+00, 1.00000e+00, 2.94810e+04, 6.66530e+04, 6.00000e+01],
       [0.00000e+00, 1.00000e+00, 2.94820e+04, 5.97360e+04, 6.00000e+01]])

In [22]:
y = merged.iloc[:,-2].values


In [23]:
y

array([0, 1, 0, ..., 1, 0, 0], dtype=int64)

In [24]:
from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state=0)

C:\ProgramData\Anaconda\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test =sc.transform(x_test)

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
classifier = LogisticRegression(random_state = 0)

In [28]:
classifier.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [29]:
y_pred = classifier.predict(x_test)

In [30]:
y_test
y_pred


array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [31]:
print(y_test)
print(y_pred)

[1 0 1 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [32]:
from sklearn.metrics import confusion_matrix

In [33]:
cm = confusion_matrix(y_test, y_pred)

In [34]:
cm

array([[2464,  290],
       [ 946,  401]], dtype=int64)

In [35]:
from sklearn.neighbors import KNeighborsClassifier
classifier2 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski',p=2 )

In [36]:
classifier2.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [37]:
y_predd = classifier2.predict(x_test)

In [38]:
cm2 = confusion_matrix(y_test, y_predd)

In [39]:
cm2

array([[2306,  448],
       [ 661,  686]], dtype=int64)

In [40]:
from sklearn.metrics import mean_squared_error
from math import sqrt


In [41]:
msr = mean_squared_error(y_test, y_pred)

In [42]:
msr

0.3013899049012436

In [43]:
RMSE = sqrt(msr)

In [44]:
RMSE 

0.5489898950811787

In [45]:
msr2 = mean_squared_error(y_test, y_predd)

In [46]:
msr2

0.2704218483296757

In [47]:
RMSE2 = sqrt(msr2)

In [48]:
RMSE2

0.5200210075849587

In [49]:
testdata = pd.read_csv('C:\\Users\\user\Downloads\microsoft datascience\FinalExam-Test\AW_test.csv')

In [50]:
print (testdata.shape)
print (testdata.CustomerID.unique().shape)

(500, 23)
(500,)


In [51]:
from dateutil.parser import parse 
from datetime import datetime

def generate_age(customer_info, format):
    collection_day = birthday = datetime(2019, 1, 1, 0, 0, 0)
    age = []
    for index, row in customer_info.iterrows():
        conv = datetime.strptime(row['BirthDate'], format)
        age.append(int((collection_day - conv).days/365))
    return age


In [52]:
testdata['Age'] = generate_age(testdata, '%m/%d/%Y')

In [53]:
testdata['Age'] += 1

In [54]:
testdata_x = testdata.loc[:,['CustomerID','YearlyIncome','Gender','Age']].values

In [55]:
testdata_x


array([[18988, 86931, 'F', 75],
       [29135, 100125, 'M', 55],
       [12156, 103985, 'F', 86],
       ...,
       [14500, 138097, 'F', 82],
       [22223, 101465, 'F', 62],
       [29068, 19108, 'F', 72]], dtype=object)

In [56]:

testdata_x[:,2] = labelencoder_x.fit_transform(testdata_x[:,2])
onehotencoder = OneHotEncoder(categorical_features=[2])
testdata_x = onehotencoder.fit_transform(testdata_x).toarray()

In [57]:

scaled_instances = sc.transform(testdata_x)
print(scaled_instances)


[[ 1.01729991 -1.01729991 -0.22663369  0.21837654  1.56932277]
 [-0.98299429  0.98299429  1.67036025  0.55032799 -0.21038051]
 [ 1.01729991 -1.01729991 -1.50388437  0.64744278  2.54815958]
 ...
 [ 1.01729991 -1.01729991 -1.06567073  1.5056759   2.19221892]
 [ 1.01729991 -1.01729991  0.37815348  0.58404142  0.41251564]
 [ 1.01729991 -1.01729991  1.65783452 -1.48800082  1.30236728]]


In [61]:
BikeBuyer = classifier2.predict(scaled_instances)

In [62]:
BikeBuyer


array([0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,

In [63]:
%pastebin 1-62

'http://dpaste.com/3DVS1CF'

In [65]:
np.savetxt('bikebuyerpred.csv', BikeBuyer, delimiter=',') 